name: test
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Archive binary
        run: |
          cd target/${{ matrix.target }}/release
          shasum -a 256 douban-api-rs > douban-api-rs.sha256
          chmod +x douban-api-rs
          tar czvf douban-api-rs-${{ matrix.target }}.tar.gz douban-api-rs douban-api-rs.sha256
          cd -
      - name: Upload binary artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}-bin
          path: target/${{ matrix.target }}/release/douban-api-rs-${{ matrix.target }}.tar.gz
          if-no-files-found: error

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Archive binary
        run: |
          cd target/${{ matrix.target }}/release
          makecab douban-api-rs.exe douban-api-rs-${{ matrix.target }}.zip 
          cd -
      - name: Upload binary artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}-bin
          path: target/${{ matrix.target }}/release/douban-api-rs-${{ matrix.target }}.zip
          if-no-files-found: error
